### ISSUE TITLE
share_plusパッケージと組み合わせて利用するとクラッシュするケースがある

### ISSUE THREAD

**Issue by K9i-0** [payjp/payjp-flutter-plugin#73]
# 概要
- こちらのパッケージを[share_plus](https://pub.dev/packages/share_plus)パッケージと組み合わせて利用したところ、Androidでクラッシュするケースがありました。

# 再現条件
- Android向けにビルドし、share_plusのshareXFilesでファイルをGoogle Driveに保存してアプリに戻るとクラッシュ
- 以下のリポジトリのpayjp_flutterブランチで再現できるはずです
  - share_plusの[example](https://github.com/K9i-0/plus_plugins/tree/payjp_flutter/packages/share_plus/share_plus/example)が使えます
https://github.com/K9i-0/plus_plugins/tree/payjp_flutter

# ログ
- アプリに戻ってきた時に何故かshare_plusのonActivityResultが反応して、getParcelableExtraに失敗してクラッシュしていました
```
E/AndroidRuntime(15699): FATAL EXCEPTION: main
E/AndroidRuntime(15699): Process: io.flutter.plugins.shareexample, PID: 15699
E/AndroidRuntime(15699): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=17062003, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage.legacy/enc=nral2wOsyjPcWRdWjz9OLwaDWHoO0ZKTaYuc43QFLHNb1Xb_vUmKcCxWphwwGBM8313NbvSCCQp9
E/AndroidRuntime(15699): NklxIC2kd4VCcrPe_qmgcNJmkaNMznDli3w9R38cWwVZlrzSJJBXe9ljXA==
E/AndroidRuntime(15699):  (has extras) }} to activity {io.flutter.plugins.shareexample/io.flutter.embedding.android.FlutterActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.apps.docs.common.drivecore.data.CelloEntrySpec
E/AndroidRuntime(15699): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
E/AndroidRuntime(15699): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
E/AndroidRuntime(15699): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(15699): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(15699): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(15699): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E/AndroidRuntime(15699): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15699): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(15699): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(15699): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15699): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(15699): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(15699): Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.apps.docs.common.drivecore.data.CelloEntrySpec
E/AndroidRuntime(15699): 	at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
E/AndroidRuntime(15699): 	at android.os.Parcel.readParcelable(Parcel.java:2964)
E/AndroidRuntime(15699): 	at android.os.Parcel.readValue(Parcel.java:2866)
E/AndroidRuntime(15699): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
E/AndroidRuntime(15699): 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
E/AndroidRuntime(15699): 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
E/AndroidRuntime(15699): 	at android.os.Bundle.getParcelable(Bundle.java:951)
E/AndroidRuntime(15699): 	at android.content.Intent.getParcelableExtra(Intent.java:8086)
E/AndroidRuntime(15699): 	at jp.pay.android.ui.PayjpCardFormActivity$Companion.onActivityResult(PayjpCardFormActivity.kt:110)
E/AndroidRuntime(15699): 	at jp.pay.android.PayjpCardForm.handleResult(PayjpCardForm.kt:152)
E/AndroidRuntime(15699): 	at jp.pay.flutter.CardFormModule.onActivityResult(CardFormModule.kt:90)
E/AndroidRuntime(15699): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime(15699): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime(15699): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
E/AndroidRuntime(15699): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime(15699): 	at android.app.Activity.dispatchActivityResult(Activity.java:8413)
E/AndroidRuntime(15699): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
E/AndroidRuntime(15699): 	... 11 more
I/Process (15699): Sending signal. PID: 15699 SIG: 9
```

**Comment by yatatsu** [comment]
フィードバックありがとうございます。

https://github.com/fluttercommunity/plus_plugins/blob/d606a7bd4c9e0809ffb8f964e062723c85586171/packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt#L30
share_plus側でも addActivityResultListener を使ってActivity Resultを監視しているようなので、おそらくpayjp_flutterがアクティブじゃない状態でActivityResultを受け取ろうとしてしまっているのが原因だと思われます。

修正方針としてはデタッチされたタイミングでリスナーを解除するか、startActivityForResult を使って requestCode を指定した上で回避するかで対応するのが良さそうと考えていますがどちらかは決めていません。
動作を見つつ対応を進めたいと思います。

**Comment by yatatsu** [comment]
こちら 0.5.0 にて修正してバージョンをリリースしました。ご確認いただければと思います:pray: @K9i-0

**Comment by K9i-0** [comment]
@yatatsu 問題発生しないこと確認できました
ありがとうございます❗️✨🤟😁👍
